# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "dynport_tools"
  s.version = "0.2.22"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tobias Schwab"]
  s.date = "2012-02-28"
  s.description = "Collection of various tools"
  s.email = "tobias.schwab@dynport.de"
  s.executables = ["redis_dumper", "xmldiff"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".document",
    ".rbenv-version",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "autotest/discover.rb",
    "bin/redis_dumper",
    "bin/xmldiff",
    "dynport_tools.gemspec",
    "lib/dynport_tools.rb",
    "lib/dynport_tools/ascii_table.rb",
    "lib/dynport_tools/deep_merger.rb",
    "lib/dynport_tools/differ.rb",
    "lib/dynport_tools/embedded_redis.rb",
    "lib/dynport_tools/eta.rb",
    "lib/dynport_tools/features.rb",
    "lib/dynport_tools/have_attributes.rb",
    "lib/dynport_tools/jenkins.rb",
    "lib/dynport_tools/jenkins/project.rb",
    "lib/dynport_tools/jenkins/remote_project.rb",
    "lib/dynport_tools/job_dsl.rb",
    "lib/dynport_tools/log_tracer.rb",
    "lib/dynport_tools/redis_dumper.rb",
    "lib/dynport_tools/redis_q.rb",
    "lib/dynport_tools/services.rb",
    "lib/dynport_tools/settings.rb",
    "lib/dynport_tools/xml_file.rb",
    "spec/dynport_tools/ascii_table_spec.rb",
    "spec/dynport_tools/deep_merger_spec.rb",
    "spec/dynport_tools/differ_spec.rb",
    "spec/dynport_tools/embedded_redis_spec.rb",
    "spec/dynport_tools/eta_spec.rb",
    "spec/dynport_tools/features_spec.rb",
    "spec/dynport_tools/have_attributes_spec.rb",
    "spec/dynport_tools/jenkins/project_spec.rb",
    "spec/dynport_tools/jenkins/remote_project_spec.rb",
    "spec/dynport_tools/jenkins_spec.rb",
    "spec/dynport_tools/job_dsl_spec.rb",
    "spec/dynport_tools/log_tracer_spec.rb",
    "spec/dynport_tools/redis_dumper_spec.rb",
    "spec/dynport_tools/redis_q_spec.rb",
    "spec/dynport_tools/services_spec.rb",
    "spec/dynport_tools/settings_spec.rb",
    "spec/dynport_tools/xml_file_spec.rb",
    "spec/dynport_tools_spec.rb",
    "spec/fixtures/file_a.xml",
    "spec/fixtures/jenkins_job.xml",
    "spec/fixtures/solr_admin.html",
    "spec/spec_helper.rb",
    "spec/xml_diff_spec.rb"
  ]
  s.homepage = "http://github.com/tobstarr/dynport_tools"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Collection of various tools"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<redis>, [">= 0"])
      s.add_runtime_dependency(%q<typhoeus>, [">= 0"])
      s.add_runtime_dependency(%q<term-ansicolor>, [">= 0"])
      s.add_runtime_dependency(%q<diff-lcs>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["= 2.8.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<ZenTest>, ["= 4.5.0"])
      s.add_development_dependency(%q<autotest>, [">= 0"])
      s.add_development_dependency(%q<autotest-growl>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
      s.add_development_dependency(%q<timecop>, [">= 0"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<growl>, [">= 0"])
      s.add_development_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_development_dependency(%q<spork>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<typhoeus>, [">= 0"])
      s.add_dependency(%q<term-ansicolor>, [">= 0"])
      s.add_dependency(%q<diff-lcs>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, ["= 2.8.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ZenTest>, ["= 4.5.0"])
      s.add_dependency(%q<autotest>, [">= 0"])
      s.add_dependency(%q<autotest-growl>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
      s.add_dependency(%q<timecop>, [">= 0"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<growl>, [">= 0"])
      s.add_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_dependency(%q<spork>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<typhoeus>, [">= 0"])
    s.add_dependency(%q<term-ansicolor>, [">= 0"])
    s.add_dependency(%q<diff-lcs>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, ["= 2.8.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ZenTest>, ["= 4.5.0"])
    s.add_dependency(%q<autotest>, [">= 0"])
    s.add_dependency(%q<autotest-growl>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
    s.add_dependency(%q<timecop>, [">= 0"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<growl>, [">= 0"])
    s.add_dependency(%q<rb-fsevent>, [">= 0"])
    s.add_dependency(%q<spork>, [">= 0"])
  end
end

